language: node_js
dist: bionic
node_js:
  - 'node'
  - 'lts/*'
  - 'lts/-1'
  - 'lts/-2'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_success: 'npm run coveralls'
